name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.4.0
      # Transform the tokens
      - run: npx design-tokens-cli transform
      # Add files that were created during a run
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Tokens
